_main:
     resource: "@BlogWebBundle/Controller/MainController.php"
     type:     annotation

_users:
     resource: "@BlogWebBundle/Controller/UsersController.php"
     type:     annotation

_blogs:
     resource: "@BlogWebBundle/Controller/BlogsController.php"
     type:     annotation

_posts:
     resource: "@BlogWebBundle/Controller/PostsController.php"
     type:     annotation
