_main:
     resource: "@BlogWeb/Controller/MainController.php"
     type:     annotation

_users:
     resource: "@BlogWeb/Controller/UsersController.php"
     type:     annotation

_posts:
     resource: "@BlogWeb/Controller/PostsController.php"
     type:     annotation

_comments:
     resource: "@BlogWeb/Controller/CommentsController.php"
     type:     annotation
