security:
    acl:
  
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            users:
                admin: { password: pa$$word, roles: [ 'ROLE_USER' ] }

    firewalls:
        profiler:
            pattern:     /_profiler.*
            security:    false

        wdt:
            pattern:     /_wdt.*
            security:    false

        configurator:
            pattern:     /_configurator.*
            security:    false

        web_login_or_signup:
            pattern:      (?:/users/login|/users/signup)
            form_login:  false
            security:    false

        web_main:
            pattern:     (?!/users/(?:login|signup)).*
            logout:      { path: /users/logout, target: /users/login }
            form_login:
                check_path:                     /users/login
                login_path:                     /users/login
                failure_path:                   null
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    true
