security:
    acl:
  
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            users:
                admin: { password: pa$$word, roles: [ 'ROLE_USER' ] }

    firewalls:
        profiler:
            pattern:  /_profiler.*
            security: false
            #security: true
            #http_basic: true

        wdt:
            pattern:  /_wdt.*
            security: false
            #security: true
            #http_basic: true

        configurator:
            pattern:  /_configurator.*
            security: false
            #security: true
            #http_basic: true
        
        main:
            logout:     { path: /users/logout, target: /users/login }
            form_login:
#                check_path:                     /users/login-check
                check_path:                     /users/login
                login_path:                     /users/login
                failure_path:                   null
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    true

#        default:
#            form_login: ~
#            anonymous:  ~
#            logout:     ~

#    role_hierarchy:
#        AUTHENTICATED: NOT_AUTHENTICATED
#    access_control:
#        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    role_hierarchy:
        IS_AUTHENTICATED_FULLY: IS_AUTHENTICATED_ANONYMOUSLY

    access_control:
#        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        # roles: NOT_AUTHENTICATED
        - { path: /users/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /users/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # roles: AUTHENTICATED
        - { path: (?!/users/(?:login|signup)), roles: IS_AUTHENTICATED_FULLY }
