Blog\WebBundle\Entity\Posts:
  type: entity
  table: posts
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 255
      fixed: false
      nullable: false
    content:
      type: text
      nullable: false
    uid:
      type: integer
      unsigned: false
      nullable: false
  lifecycleCallbacks: {  }
