Blog\WebBundle\Entity\Users:
  type: entity
  table: users
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    login:
      type: string
      length: 255
      fixed: false
      nullable: false
    email:
      type: string
      length: 255
      fixed: false
      nullable: false
    password:
      type: string
      length: 32
      fixed: false
      nullable: false
    firstName:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: first_name
    secondName:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: second_name
  lifecycleCallbacks: {  }
